version: '3.8'

services:
  files-service:
    build:
      context: ../files
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ../../envs/files.env
    environment:
      - DB_HOST=files-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=files
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=miniosecret
    depends_on:
      - files-db
      - minio
    networks:
      - files-network

  files-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=files
    volumes:
      - files-db-data:/var/lib/postgresql/data
      - ../../services/files/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - files-network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=miniosecret
    volumes:
      - minio-data:/data
    networks:
      - files-network

volumes:
  files-db-data:
  minio-data:

networks:
  files-network:
    driver: bridge